# Configuration file for user settings
# This file should include the path for toolchain and other settings that user would like to override.
# Example toolchain path definitions
set(CMAKE_FIND_ROOT_PATH "D:/e2/gcc-arm-none-eabi-10.3-2021.10/bin")


set(COMPILER_OPTIMIZATION "-O2")
string(REPLACE "-O0" ${COMPILER_OPTIMIZATION} RASC_CMAKE_CXX_FLAGS "${RASC_CMAKE_CXX_FLAGS}")
string(REPLACE "-O0" ${COMPILER_OPTIMIZATION} RASC_CMAKE_C_FLAGS "${RASC_CMAKE_C_FLAGS}")
string(REPLACE "-O0" ${COMPILER_OPTIMIZATION} RASC_CMAKE_ASM_FLAGS "${RASC_CMAKE_ASM_FLAGS}")


SET(RASC_CMAKE_C_FLAGS "-I ${CMAKE_CURRENT_SOURCE_DIR}/src/u8g2/csrc ${RASC_CMAKE_C_FLAGS}")
SET(RASC_CMAKE_C_FLAGS "-I ${CMAKE_CURRENT_SOURCE_DIR}/src/u8g2/cppsrc ${RASC_CMAKE_C_FLAGS}")

SET(RASC_CMAKE_CXX_FLAGS "-I ${CMAKE_CURRENT_SOURCE_DIR}/src/u8g2/csrc ${RASC_CMAKE_CXX_FLAGS}")
SET(RASC_CMAKE_CXX_FLAGS "-I ${CMAKE_CURRENT_SOURCE_DIR}/src/u8g2/cppsrc ${RASC_CMAKE_CXX_FLAGS}")

SET(RASC_CMAKE_ASM_FLAGS "-I ${CMAKE_CURRENT_SOURCE_DIR}/src/u8g2/csrc ${RASC_CMAKE_ASM_FLAGS}")
SET(RASC_CMAKE_ASM_FLAGS "-I ${CMAKE_CURRENT_SOURCE_DIR}/src/u8g2/cppsrc ${RASC_CMAKE_ASM_FLAGS}")



